Development
FutureWorkForce/materom-plasare-comanda-dispatcher pull request #1
Opened 2022-11-15 13:13 UTC by cileaalex

Sunt ceva chestii legate de top level selector pe WF Analyzer... nu stiu ce-i cu ele, selectorii merg bine.

2022-11-17 07:46 UTC, andreia-fratila requested changes
Pe langa commnenturile adaugate, in loc de Config.xlsx ar trebui sa fie Config.Json cum e si in SDD

2022-11-17 07:46 UTC, andreia-fratila commented on ApplicationLayer/SRM/SRM_Logon.xaml
> +              </ui:Click.Target>
Poti folosi simulate pentru activitatile de aici

2022-11-17 07:46 UTC, andreia-fratila commented on ApplicationLayer/SAP/SAP_Logon.xaml
> +    <ucas:Login Password="{x:Null}" Window="{x:Null}" Client="200" DisplayName="Login to SAP" sap:VirtualizedContainerService.HintSize="338,380" sap2010:WorkflowViewState.IdRef="Login_1" IsSecure="Tr
poti adauga client si language in config

2022-11-17 07:46 UTC, andreia-fratila commented on ApplicationLayer/SAP/SAP_Logon.xaml
> +    <ui:GetRobotCredential AssetName="SAP_Credential" CacheStrategy="None" DisplayName="Get SAP Credentials" FolderPath="PlasareComanda_Dispatcher" sap:VirtualizedContainerService.HintSize="338,62" s
adauga path-ul in Config + redenumire activitate

2022-11-17 07:46 UTC, andreia-fratila commented on BusinessLayer/ExtractOrdersTable.xaml
> +    <x:Property Name="dt_TransactionData" Type="InOutArgument(sd:DataTable)" />
verifica naming convention pentru argumente

2022-11-17 07:46 UTC, andreia-fratila commented on BusinessLayer/ExtractOrdersTable.xaml
> +            </If>
as extrage si partea asta intr-un workflow separat in data layer

2022-11-17 07:46 UTC, andreia-fratila commented on ApplicationLayer/SRM/SRM_DisplayOrderItems.xaml
> +            <uix:NCheckState DisplayName="Check &quot;green check&quot; Exists" sap:VirtualizedContainerService.HintSize="638,323" sap2010:WorkflowViewState.IdRef="NCheckState_1" Timeout="2" Version=
adauga timeout-ul in Config

2022-11-17 07:46 UTC, andreia-fratila commented on ApplicationLayer/SRM/SRM_DisplayOrderItems.xaml
> +            </ui:TypeInto>
verifica selectorii din activitatile de aici, e suprascris selectorul din attach window

2022-11-17 07:46 UTC, andreia-fratila commented on ApplicationLayer/SRM/SRM_DisplayOrderItems.xaml
> +            <ui:Click AlterIfDisabled="{x:Null}" DelayBefore="{x:Null}" DelayMS="{x:Null}" SendWindowMessages="{x:Null}" SimulateClick="{x:Null}" ClickType="CLICK_SINGLE" DisplayName="Maximize order
la fel si aici

2022-11-17 07:46 UTC, andreia-fratila commented on ApplicationLayer/SRM/SRM_ExtractOrderItemsTable.xaml
> +    <uix:NApplicationCard AttachMode="ByInstance" DisplayName="Use SRM Orders Window" sap:VirtualizedContainerService.HintSize="434,392" sap2010:WorkflowViewState.IdRef="NApplicationCard_1" Interacti
adauga linkul in config

2022-11-17 07:46 UTC, andreia-fratila commented on ApplicationLayer/SRM/SRM_ExtractOrderItemsTable.xaml
> +    <x:Property Name="out_dt_orderItems" Type="OutArgument(sd:DataTable)" />
verifica naming convetion, [in, io, out]_dtVariableName

2022-11-17 07:46 UTC, andreia-fratila commented on ApplicationLayer/SRM/SRM_ExtractOrderItemsTable.xaml
> +    </ui:ForEachRow>
extrage partea de procesare de date intr-un workflow separat in data layer

2022-11-17 07:46 UTC, andreia-fratila commented on ApplicationLayer/SAP/SAP_ProcessOrder.xaml
> +    <uix:NApplicationCard AttachMode="ByInstance" DisplayName="Use SAP Window" sap:VirtualizedContainerService.HintSize="534,2784" sap2010:WorkflowViewState.IdRef="NApplicationCard_1" ScopeGuid="fa24
adauga path-ul in config

2022-11-17 07:46 UTC, andreia-fratila commented on ApplicationLayer/SAP/SAP_ProcessOrder.xaml
> +            <ui:TypeInto AlterIfDisabled="{x:Null}" ClickBeforeTyping="{x:Null}" DelayBefore="{x:Null}" DelayBetweenKeys="{x:Null}" DelayMS="{x:Null}" EmptyField="{x:Null}" SendWindowMessages="{x:Nul
adauga valorile  hardcoded in config
verifica selectorii din workflow, e suprascris selectorul pentru fereastra

2022-11-17 07:46 UTC, andreia-fratila commented on ApplicationLayer/SAP/SAP_ProcessOrder.xaml
> +            <ui:TypeInto AlterIfDisabled="{x:Null}" ClickBeforeTyping="{x:Null}" DelayBefore="{x:Null}" DelayBetweenKeys="{x:Null}" DelayMS="{x:Null}" EmptyField="{x:Null}" SendWindowMessages="{x:Nul
la fel si aici

2022-11-17 07:46 UTC, andreia-fratila commented on ApplicationLayer/SAP/SAP_ProcessOrder.xaml
> +            <TryCatch DisplayName="Try Join Tables" sap:VirtualizedContainerService.HintSize="438,411" sap2010:WorkflowViewState.IdRef="TryCatch_1">
extrage partea de procesare de date intr-un workflow separat

2022-11-17 07:46 UTC, andreia-fratila commented on ApplicationLayer/SAP/SAP_ProcessOrder.xaml
> +                <ui:InvokeCode ContinueOnError="{x:Null}" Code="parentTable.Columns.Add(&quot;pretSAP&quot;)&#xA;For Each parentrow As system.data.datarow In parentTable.Rows&#xA;&#xA;&#x9;For Each c
poti inlocui al doilea for each cu un linq

2022-11-17 07:46 UTC, andreia-fratila commented on ApplicationLayer/SAP/SAP_ProcessOrder.xaml
> +    <ui:AddQueueItem ServiceBaseAddress="{x:Null}" DisplayName="Add Order Details to queue" FolderPath="PlasareComanda_Dispatcher" sap:VirtualizedContainerService.HintSize="534,61" sap2010:WorkflowVi
adauga orchestrator folder path in config

2022-11-17 08:11 UTC, cileaalex commented on ApplicationLayer/SRM/SRM_Logon.xaml
> +              </ui:Click.Target>
Done, nu garantez totusi aceeasi stabilitate. Eu de aia am renuntat la simulate

2022-11-17 08:13 UTC, cileaalex commented on ApplicationLayer/SAP/SAP_Logon.xaml
> +    <ucas:Login Password="{x:Null}" Window="{x:Null}" Client="200" DisplayName="Login to SAP" sap:VirtualizedContainerService.HintSize="338,380" sap2010:WorkflowViewState.IdRef="Login_1" IsSecure="Tr
Done

2022-11-17 08:17 UTC, cileaalex commented on ApplicationLayer/SAP/SAP_Logon.xaml
> +    <ui:GetRobotCredential AssetName="SAP_Credential" CacheStrategy="None" DisplayName="Get SAP Credentials" FolderPath="PlasareComanda_Dispatcher" sap:VirtualizedContainerService.HintSize="338,62" s
Sper ca te refereai la "Open SAP", Done

2022-11-17 08:20 UTC, cileaalex commented on BusinessLayer/ExtractOrdersTable.xaml
> +    <x:Property Name="dt_TransactionData" Type="InOutArgument(sd:DataTable)" />
Done.. era mai usor sa le autocompleteze :D

2022-11-17 08:31 UTC, cileaalex commented on ApplicationLayer/SRM/SRM_DisplayOrderItems.xaml
> +            <uix:NCheckState DisplayName="Check &quot;green check&quot; Exists" sap:VirtualizedContainerService.HintSize="638,323" sap2010:WorkflowViewState.IdRef="NCheckState_1" Timeout="2" Version=
Done

2022-11-17 08:51 UTC, cileaalex commented on ApplicationLayer/SRM/SRM_ExtractOrderItemsTable.xaml
> +    <uix:NApplicationCard AttachMode="ByInstance" DisplayName="Use SRM Orders Window" sap:VirtualizedContainerService.HintSize="434,392" sap2010:WorkflowViewState.IdRef="NApplicationCard_1" Interacti
Aveam in asset, doar am joinuit cu ruta

2022-11-17 08:51 UTC, cileaalex commented on ApplicationLayer/SRM/SRM_ExtractOrderItemsTable.xaml
> +    <x:Property Name="out_dt_orderItems" Type="OutArgument(sd:DataTable)" />
te referi fara _ intre dt si numele variabilei ? 
Not DONE

2022-11-17 09:06 UTC, cileaalex commented on ApplicationLayer/SRM/SRM_ExtractOrderItemsTable.xaml
> +    </ui:ForEachRow>
DONE

2022-11-17 09:14 UTC, cileaalex commented on ApplicationLayer/SAP/SAP_ProcessOrder.xaml
> +            <ui:TypeInto AlterIfDisabled="{x:Null}" ClickBeforeTyping="{x:Null}" DelayBefore="{x:Null}" DelayBetweenKeys="{x:Null}" DelayMS="{x:Null}" EmptyField="{x:Null}" SendWindowMessages="{x:Nul
le-am adaugat in config, still selectorul nu merge fara top level selector

2022-11-17 10:17 UTC, cileaalex commented on ApplicationLayer/SAP/SAP_ProcessOrder.xaml
> +            <ui:TypeInto AlterIfDisabled="{x:Null}" ClickBeforeTyping="{x:Null}" DelayBefore="{x:Null}" DelayBetweenKeys="{x:Null}" DelayMS="{x:Null}" EmptyField="{x:Null}" SendWindowMessages="{x:Nul
DONE

2022-11-22 07:56 UTC, andreia-fratila requested changes

2022-11-22 07:56 UTC, andreia-fratila commented on ApplicationLayer/SAP/~SAP_ProcessOrder.xaml
> +<Activity mc:Ignorable="sap sap2010" x:Class="SAP_ProcessOrder" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
ai un fisier duplicat

2022-11-22 07:56 UTC, andreia-fratila commented on ApplicationLayer/SAP/SAP_ProcessOrder.xaml
> +            <ui:InvokeWorkflowFile ArgumentsVariable="{x:Null}" ContinueOnError="{x:Null}" DisplayName="DataLayer\AssignPricesFromSAP.xaml - Invoke Workflow File" sap:VirtualizedContainerService.Hint
extrage workflowul ce tine de data layer in afara celui din application layer

2022-11-22 07:56 UTC, andreia-fratila commented on ApplicationLayer/SRM/SRM_DisplayOrderItems.xaml
> +<Activity mc:Ignorable="sap sap2010" x:Class="SRM_DisplayOrderItems" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2
![image](https://user-images.githubusercontent.com/78911015/203255804-ed910f65-8f6f-4f1e-a148-0dc05c54f712.png)

2022-11-22 07:56 UTC, andreia-fratila commented on ApplicationLayer/SRM/SRM_DisplayOrders.xaml
> +            <ui:TypeInto AlterIfDisabled="{x:Null}" ClickBeforeTyping="{x:Null}" DelayBefore="{x:Null}" DelayBetweenKeys="{x:Null}" DelayMS="{x:Null}" SendWindowMessages="{x:Null}" SimulateType="{x:N
![image](https://user-images.githubusercontent.com/78911015/203256020-77c53a6a-713c-40e4-aec8-ff380168a53d.png)
e suprascris selectorul din container

2022-11-22 07:56 UTC, andreia-fratila commented on ApplicationLayer/SRM/SRM_ExtractOrderItemsTable.xaml
> +    <ui:InvokeWorkflowFile ArgumentsVariable="{x:Null}" ContinueOnError="{x:Null}" DisplayName="DataLayer\AdjustOrderItemsTable.xaml - Invoke Workflow File" sap:VirtualizedContainerService.HintSize="
extrage workflowul ce tine de data layer

2022-11-22 07:56 UTC, andreia-fratila commented on BusinessLayer/ExtractOrdersTable.xaml
> +                <OutArgument x:TypeArguments="sd:DataTable" x:Key="out_dt_orders">
verifica naming convetion, ar trebui sa fie acelasi in toate workflowurile

2022-11-22 07:56 UTC, andreia-fratila commented on ApplicationLayer/SRM/SRM_ExtractOrdersTable.xaml
> +        <uix:TargetApp Area="0, 0, 0, 0" BrowserType="Edge" IconBase64="iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAh4SURBVFhHpdd
url in config

2022-11-22 07:56 UTC, andreia-fratila commented on ApplicationLayer/SRM/SRM_DisplayOrderItems.xaml
> +            <ui:TypeInto AlterIfDisabled="{x:Null}" ClickBeforeTyping="{x:Null}" DelayMS="{x:Null}" SendWindowMessages="{x:Null}" Activate="True" DelayBefore="[cint(CDbl(in_config(&quot;timeoutSecond
![image](https://user-images.githubusercontent.com/78911015/203257242-3ed74ace-cd90-465a-b782-e67c449c29a7.png)

2022-11-25 09:33 UTC, cileaalex commented on ApplicationLayer/SAP/~SAP_ProcessOrder.xaml
> +<Activity mc:Ignorable="sap sap2010" x:Class="SAP_ProcessOrder" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
deleted

2022-11-25 09:52 UTC, cileaalex commented on ApplicationLayer/SRM/SRM_ExtractOrdersTable.xaml
> +        <uix:TargetApp Area="0, 0, 0, 0" BrowserType="Edge" IconBase64="iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAh4SURBVFhHpdd
dafuc am mai facut-o pe asta odata oare n-am salvat? anyways done

2022-11-25 10:15 UTC, cileaalex commented on ApplicationLayer/SAP/SAP_ProcessOrder.xaml
> +            <ui:InvokeWorkflowFile ArgumentsVariable="{x:Null}" ContinueOnError="{x:Null}" DisplayName="DataLayer\AssignPricesFromSAP.xaml - Invoke Workflow File" sap:VirtualizedContainerService.Hint
done

2022-11-25 10:15 UTC, cileaalex commented on ApplicationLayer/SRM/SRM_DisplayOrderItems.xaml
> +<Activity mc:Ignorable="sap sap2010" x:Class="SRM_DisplayOrderItems" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2
done

2022-11-25 10:23 UTC, cileaalex commented on ApplicationLayer/SRM/SRM_DisplayOrders.xaml
> +            <ui:TypeInto AlterIfDisabled="{x:Null}" ClickBeforeTyping="{x:Null}" DelayBefore="{x:Null}" DelayBetweenKeys="{x:Null}" DelayMS="{x:Null}" SendWindowMessages="{x:Null}" SimulateType="{x:N
done

2022-11-25 10:25 UTC, cileaalex commented on ApplicationLayer/SRM/SRM_ExtractOrderItemsTable.xaml
> +    <ui:InvokeWorkflowFile ArgumentsVariable="{x:Null}" ContinueOnError="{x:Null}" DisplayName="DataLayer\AdjustOrderItemsTable.xaml - Invoke Workflow File" sap:VirtualizedContainerService.HintSize="
done

2022-11-25 10:28 UTC, cileaalex commented on ApplicationLayer/SRM/SRM_DisplayOrderItems.xaml
> +            <ui:TypeInto AlterIfDisabled="{x:Null}" ClickBeforeTyping="{x:Null}" DelayMS="{x:Null}" SendWindowMessages="{x:Null}" Activate="True" DelayBefore="[cint(CDbl(in_config(&quot;timeoutSecond
done

2022-12-09 14:23 UTC, andreia-fratila approved these changes

2022-12-09 14:23 UTC, merged